customhost = "employeedb.c5kx03zfr7wn.us-east-1.rds.amazonaws.com" 
customuser = "eruobodo"
custompass = "password123"
customdb = "employeedb"
custombucket = "prod-employeedb"
customregion = "us-east-1"
